# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build Home Application (CI)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install .NET MAUI
      run: dotnet workload install maui
    - name: Restore dependencies
      run: dotnet restore

    - name: Replace Variables in appsettings.json
      run: |
          sed -i "s|{{SYNCFUSION_LICENCE_KEY}}|${{secrets.SYNCFUSION_LICENCE_KEY}}|g" Mobile/Mobile/appsettings.json
          sed -i "s|{{MOBILE_REALM_APPID}}|${{secrets.MOBILE_REALM_APPID}}|g" Mobile/Mobile/appsettings.json
          sed -i "s|{{MOBILE_REALM_EMAIL_ADDRESS}}|${{secrets.MOBILE_REALM_EMAIL_ADDRESS}}|g" Mobile/Mobile/appsettings.json
          sed -i "s|{{MOBILE_REALM_PASSWORD}}|${{secrets.MOBILE_REALM_PASSWORD}}|g" Mobile/Mobile/appsettings.json

    - name: Decode keystore secret
      run: |
          $base64Content = "${{ secrets.ANDROID_KEYSTORE_BASE64_CONTENT }}"
          # Decode the keystore secret
          $keystoreBytes = [System.Convert]::FromBase64String($base64Content)
          # Write the decoded keystore bytes to a file
          [System.IO.File]::WriteAllBytes("BootComHome.keystore", $keystoreBytes)
                
    - name: Build
      run: dotnet build Mobile/Mobile/Mobile.csproj -c Release -f net8.0-android --no-restore /p:AndroidSigningKeyStore=BootComHome.keystore /p:AndroidSigningKeyAlias="${{ secrets.ANDROID_KEYSTORE_ALIAS }}" /p:AndroidSigningKeyPass="${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" /p:AndroidSigningStorePass="${{ secrets.ANDROID_KEYSTORE_ALIAS_PASSWORD }}"

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        path: |
          ./**/*.aab
          ./**/*.apk

    - name: Publish Google Play
      uses: akiojin/publish-googleplay-github-action@v0.1.3
      with:
      # Specify the path of the Android App Bundle file to upload.
        aab-path: Mobile\obj\Release\net8.0-android\android\bin\co.uk.bootcom.home.aab
        service-account-key: "${{ secrets.ANDROID_GOOGLE_PLAY_SERVICE_KEY_JSON }}"
        # Specifies the track to be uploaded. Valid values are: alpha, beta, production, and internal.
        track: internal
        package-name: co.uk.bootcom.home
    
    
          
  
