# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build Home Application (CI)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install .NET MAUI
      run: dotnet workload install maui
    - name: Restore dependencies
      run: dotnet restore

    - name: Replace Variables in appsettings.json
      run: |
          sed -i "s|{{SYNCFUSION_LICENCE_KEY}}|${{secrets.SYNCFUSION_LICENCE_KEY}}|g" Mobile/Mobile/appsettings.json
          sed -i "s|{{MOBILE_REALM_APPID}}|${{secrets.MOBILE_REALM_APPID}}|g" Mobile/Mobile/appsettings.json
          sed -i "s|{{MOBILE_REALM_EMAIL_ADDRESS}}|${{secrets.MOBILE_REALM_EMAIL_ADDRESS}}|g" Mobile/Mobile/appsettings.json
          sed -i "s|{{MOBILE_REALM_PASSWORD}}|${{secrets.MOBILE_REALM_PASSWORD}}|g" Mobile/Mobile/appsettings.json
      
    - name: Build
      run: dotnet build Mobile/Mobile/Mobile.csproj -c Release -f net8.0-android --no-restore
