# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Deploy to Google Play Store

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install .NET MAUI
      run: dotnet workload install maui

    - name: Restore dependencies
      run: dotnet restore

    - name: Replace Variables in appsettings.json
      uses: Nambers/ReplaceStringInFile@v1
      with:
        path: "D:\\\\a\\\\home\\\\home\\\\Mobile\\\\Mobile\\\\bin\\\\Release\\\\net8.0-android\\\\publish\\\\appsettings.json"
        oldStringWin: "{{SYNCFUSION_LICENCE_KEY}}"
        newStringWin: "${{secrets.SYNCFUSION_LICENCE_KEY}}"
        showFileContent: true

    - name: Replace Variables in appsettings.json
      run: sed -i "s|{{SYNCFUSION_LICENCE_KEY}}|${{secrets.SYNCFUSION_LICENCE_KEY}}|g" "D:\\\\a\\\\home\\\\home\\\\Mobile\\\\Mobile\\\\bin\\\\Release\\\\net8.0-android\\\\publish\\\\appsettings.json"
          
    - name: Replace Variables in appsettings.json
      run: sed -i "s|{{MOBILE_REALM_APPID}}|${{secrets.MOBILE_REALM_APPID}}|g" "D:\\\\a\\\\home\\\\home\\\\Mobile\\\\Mobile\\\\bin\\\\Release\\\\net8.0-android\\\\publish\\\\appsettings.json
          
    - name: Replace Variables in appsettings.json
      run:  sed -i "s|{{MOBILE_REALM_EMAIL_ADDRESS}}|${{secrets.MOBILE_REALM_EMAIL_ADDRESS}}|g" "D:\\\\a\\\\home\\\\home\\\\Mobile\\\\Mobile\\\\bin\\\\Release\\\\net8.0-android\\\\publish\\\\appsettings.json
         
    - name: Replace Variables in appsettings.json
      run: sed -i "s|{{MOBILE_REALM_PASSWORD}}|${{secrets.MOBILE_REALM_PASSWORD}}|g" "D:\\\\a\\\\home\\\\home\\\\Mobile\\\\Mobile\\\\bin\\\\Release\\\\net8.0-android\\\\publish\\\\appsettings.json

   # - name: Clean      
   #   run: dotnet clean Mobile/Mobile/Mobile.csproj -c Release -f net8.0-android 
      
    - name: Bump release version
      uses: action-pack/increment@v2
      with:
        name: 'MOBILE_ANDROID_VERSION_CODE'
        token: ${{ secrets.BOOTCOM_HOME_GITHUB_PAT }}

    - uses: Amadevus/pwsh-script@v2
      name: Increment Version with Powershell
      id: increment-version
      with:
        script: '$currentVersion="${{ vars.MOBILE_ANDROID_VERSION_NAME }}";$versionParts = $currentVersion.split(".");$major = [int]$versionParts[0];$minor = [int]$versionParts[1];$patch = [int]$versionParts[2];$patch++;$newVersion = "$major.$minor.$patch";return $newVersion'
    - run: echo "${{ steps.increment-version.outputs.result }}"

    - name: Update version variable
      run: echo "VERSION=$(echo ${{ steps.increment-version.outputs.result }})" >> $env:GITHUB_ENV

    - uses: mmoyaferrer/set-github-variable@v1.0.0
      name: Update version github actions variable
      with:
        name: 'MOBILE_ANDROID_VERSION_NAME'
        value: ${{ steps.increment-version.outputs.result }}
        repository: 'bootcom-uk/home'
        token: ${{ secrets.BOOTCOM_HOME_GITHUB_PAT }}

    - name: Update AndroidManifest.xml
      uses: damienaicheh/update-android-version-manifest-action@v1.0.0
      with:
        android-manifest-path: 'Mobile/Mobile/Platforms/Android/AndroidManifest.xml'
        version-code: ${{ vars.MOBILE_ANDROID_VERSION_CODE }}
        version-name: ${{ steps.increment-version.outputs.result }}
        print-file: true

    - name: Build
      # run: dotnet build Mobile/Mobile/Mobile.csproj -c Release -f net8.0-android --no-restore /p:AndroidSigningKeyStore=BootComHome.keystore /p:AndroidSigningKeyAlias="${{ secrets.ANDROID_KEYSTORE_ALIAS }}" /p:AndroidSigningKeyPass="${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" /p:AndroidSigningStorePass="${{ secrets.ANDROID_KEYSTORE_ALIAS_PASSWORD }}"
      run: dotnet build Mobile/Mobile/Mobile.csproj -c Release -f net8.0-android --no-restore
    
    - name: Setup Keystore File
      run: |
        echo "${{ secrets.ANDROID_KEYSTORE_GPG_FILE }}" > BootComHome.keystore.asc
        gpg -d --passphrase "${{ secrets.ANDROID_KEYSTORE_GPG_PASSWORD }}" --batch BootComHome.keystore.asc > "D:\a\home\home\Mobile\Mobile\bin\Release\net8.0-android\BootComHome.keystore"
      
    - name: Publish
      run: dotnet publish Mobile/Mobile/Mobile.csproj  -f net8.0-android -c Release -p:AndroidKeyStore=true -p:AndroidSigningKeyStore="D:\a\home\home\Mobile\Mobile\bin\Release\net8.0-android\BootComHome.keystore" -p:AndroidSigningKeyAlias=${{ secrets.ANDROID_KEYSTORE_ALIAS }} -p:AndroidSigningKeyPass=${{ secrets.ANDROID_KEYSTORE_PASSWORD }} -p:AndroidSigningStorePass=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        path: |
          ./**/*.aab
        # ./**/*.apk
   
    - name: Upload .aab to Internal Track
      id: upload_internal
      uses: KevinRohn/github-action-upload-play-store@v1.0.0
      with:
        service_account_json: ${{ secrets.ANDROID_GOOGLE_PLAY_SERVICE_KEY_JSON_BASE64 }}
        package_name: "co.uk.bootcom.home"
        aab_file_path: "D:\\\\a\\\\home\\\\home\\\\Mobile\\\\Mobile\\\\bin\\\\Release\\\\net8.0-android\\\\publish\\\\co.uk.bootcom.home-Signed.aab"
        track: "internal"
        release_status: "draft" 
